export enum GroceryCategory {
  PRODUCE = 'produce',
  DAIRY = 'dairy',
  MEAT = 'meat',
  PANTRY = 'pantry',
  BEVERAGES = 'beverages',
  SNACKS = 'snacks',
  VEGETABLES = 'vegetables',
  FRUITS = 'fruits',
  BAKERY = 'bakery',
  SEAFOOD = 'seafood',
  CONDIMENTS = 'condiments',
  SPICES = 'spices',
  HERBS = 'herbs',
  NUTS = 'nuts',
  SEEDS = 'seeds',
  OTHER = 'other',
}
